export enum Secrets {
  CLERK_SECRET_KEY = "CLERK_SECRET_KEY",
  CLERK_WEBHOOK_SECRET = "CLERK_WEBHOOK_SECRET",
  CLERK_WEBHOOK_SECRET_PROD = "CLERK_WEBHOOK_SECRET_PROD",
  MAILGUN_API_KEY = "MAILGUN_API_KEY",
  MAILGUN_DOMAIN = "MAILGUN_DOMAIN",
  MAILGUN_URL = "MAILGUN_URL", // Optional: EU endpoint "https://api.eu.mailgun.net"
  GOOGLE_OAUTH_CLIENT_ID = "GOOGLE_OAUTH_CLIENT_ID",
  GOOGLE_OAUTH_CLIENT_SECRET = "GOOGLE_OAUTH_CLIENT_SECRET",
}
