export enum DatabaseCollection {
  USERS = "users",
  APPOINTMENTS = "appointments",
  CALENDARS = "calendars",
  CALENDAR_SYNC_CONNECTIONS = "calendar-sync-connections",
  MEMBERS = "members",
  ORGANIZATIONS = "organizations",
  ROLES = "roles",
  SERVICES = "services",
  CUSTOMERS = "customers",
  TIME_OFF = "time-off",
  INVITES = "invites",
  API_KEY_HASHES = "api-key-hashes",
  WEBHOOK_SUBSCRIPTIONS = "webhook-subscriptions",
}
